const fs = require('fs');

const path = './src/data/translations.js';
let content = fs.readFileSync(path, 'utf8');

const newKeys = {
  goodMorning: "Good Morning",
  goodAfternoon: "Good Afternoon",
  goodEvening: "Good Evening",
  goodNight: "Good Night",
  health_plan_today: "Here is your health plan for today",
  care_pulse: "Care Pulse",
  sos_emergency: "SOS Emergency",
  todays_medicines: "Today's Medicines",
  next_appointment: "Next Appointment",
  caregiver_linked_title: "Caregiver Linked",
  status_linked: "Linked",
  call_caregiver: "Call Caregiver",
  alert_caregiver: "Alert Caregiver",
  quick_actions: "Quick Actions",
  ai_chat: "AI Health Chat",
  ai_chat_desc: "Ask health doubts safely",
  voice_assistant: "Voice Assistant",
  voice_assistant_desc: "Speak instead of typing",
  emergency: "Emergency SOS",
  emergency_sos_desc: "Call 112 and alert caregiver",
  profile: "Health Profile",
  health_profile_desc: "Manage medical details",
  reports: "Reports",
  reports_desc: "View medicine adherence",
  my_medicines: "My Medicines",
  appointments: "Appointments",
  mark_taken: "Mark Taken",
  skip: "Skip",
  remind_later: "Remind Later",
  pending: "Pending",
  taken: "Taken",
  skipped: "Skipped",
  pending_later: "Remind Later",
  view_all: "View All",
  medicine_skipped_alert: "Medicine skipped. Caregiver alert created.",
  medicine_marked_taken: "Medicine marked as taken.",
  reminder_delayed: "Reminder delayed.",
  add_medicine: "Add Medicine",
  edit_medicine: "Edit Medicine",
  delete_medicine: "Delete Medicine",
  morning: "Morning",
  afternoon: "Afternoon",
  night: "Night",
  dosage: "Dosage",
  frequency: "Frequency",
  time: "Time",
  start_date: "Start Date",
  notes: "Notes",
  reminder_channel: "Reminder Channel",
  app_notification: "App Notification",
  whatsapp: "WhatsApp",
  sms: "SMS",
  ivr_call: "IVR Call",
  book_appointment: "Book Appointment",
  edit_appointment: "Edit Appointment",
  cancel_appointment: "Cancel Appointment",
  department: "Department",
  date: "Date",
  reason: "Reason",
  mode: "Mode",
  online: "Online",
  hospital_visit: "Hospital Visit",
  aiDisclaimer: "This is general guidance, not a replacement for doctor consultation.",
  get_location: "Get Current Location",
  send_alert: "Send Emergency Alert",
  emergency_alert_sent: "Emergency alert sent to caregiver, doctor, and hospital admin.",
  dial_112: "Dial 112 for emergency support.",
  blood_group: "Blood Group",
  address: "Address",
  allergies: "Allergies",
  current_medicines: "Current Medicines",
  preferred_language: "Preferred Language",
  font_size: "Font Size",
  high_contrast: "High Contrast",
  notifications: "Notifications",
  save_profile: "Save Profile",
  adherence: "Adherence",
  emergency_history: "Emergency History",
  missed_medicines: "Missed Medicines",
  somethingWentWrong: "Something went wrong.",
  returnToDashboard: "Return to Dashboard",
  settings: "Settings",
  doctor_name: "Doctor Name",
  patient_name: "Patient Name",
  clinical_review_center: "Clinical Review Center",
  patient_monitoring_center: "Patient Monitoring Center",
  accept: "Accept",
  reject: "Reject",
  complete: "Complete",
  in_progress: "In Progress",
  completed: "Completed",
  mark_in_progress: "Mark In Progress",
  mark_completed: "Mark Completed",
  resolve: "Resolve",
  mark_read: "Mark Read",
  save_note: "Save Note",
  clear: "Clear",
  send_whatsapp: "Send WhatsApp",
  alert_doctor: "Alert Doctor",
  remind_patient: "Remind Patient",
  today_appointments: "Today's Appointments",
  emergency_requests: "Emergency Requests",
  total_patients: "Total Patients",
  recent_consultation: "Recent Consultation",
  linked_patient_card: "Linked Patient",
  today_medicine_status: "Today's Medicine Status",
  unread_alerts: "Unread Alerts",
  last_emergency: "Last Emergency",
  no_active_emergencies: "No active emergencies",
  no_pending_appointments: "No pending appointments",
  no_recent_consultations: "No recent consultations",
  call_patient: "Call Patient",
  patient_details: "Patient Details",
  hospital_operations_center: "Hospital Operations Center",
  missed_medicines_today: "Missed Medicines Today",
  active_emergencies: "Active Emergencies",
  total_doctors: "Total Doctors",
  pending_appointments: "Pending Appointments",
  recent_alerts_feed: "Recent Alerts",
  mark_missed: "Mark Missed",
  cancel_appointment: "Cancel Appointment",
  export_report: "Export Report",
  doctor_workload: "Doctor Workload",
  adherence_overview: "Adherence Overview",
  view_patient: "View Patient",
  call_caregiver: "Call Caregiver",
  patient_count_by_condition: "Patient Count by Condition"
};

// Extremely naive approach: we'll just inject these directly into the export const translations = { ... }
// We can use a regex to find each language block and append.

const langs = ['en', 'ta', 'te', 'ml', 'kn', 'hi'];

langs.forEach(lang => {
  const regex = new RegExp(`(${lang}:\\s*{)`, 'g');
  let injected = Object.entries(newKeys).map(([k, v]) => `    ${k}: "${v}",`).join('\n');
  content = content.replace(regex, `$1\n${injected}`);
});

fs.writeFileSync(path, content, 'utf8');
console.log('Keys injected.');
